### PR TITLE
add new biz binarykitchen from NZ

### PR DESCRIPTION
**Pull request by binarykitchen**
yo - thanks for this!

### CODE REVIEW

**Comment by kratsg** [comment]
@binarykitchen - np! Just an FYI, but before this gets merged in, (and I need to detail this on the readme), do you want to add additional things? E.G. look at #29:

```json
{
    "category": "Creative services and business consulting",
    "comments": "null",
    "location": "Washington DC",
    "name": "Eyeth Studios",
    "url": "http://www.eyethstudios.com",
    "lastUpdated": "12/4/2018 2:56:46"
} 
```

**Comment by binarykitchen** [comment]
@kratsg right, thanks. updated.

**Comment by kratsg** [comment]
Can you use (I know, I know) the American date standard:

`    "lastUpdated": "12/4/2018 17:45:00"`

**Comment by binarykitchen** [comment]
alright, here you go

**Comment by kratsg** [comment]
you're live

**Pull request merged**
